- hosts: master_nodes
  become: yes
  roles:
    - role: elasticsearch
  vars:
    es_instance_name: "node1"
    es_heap_size: "1g"
    es_config:
      cluster.name: "hawk-cluster"
      discovery.zen.ping.unicast.hosts: "ip-172-31-25-114.us-west-2.compute.internal:9300"
      http.port: 9200
      transport.tcp.port: 9300
      node.data: false
      node.master: true
      bootstrap.memory_lock: false
      network.host : '172.31.25.114'
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_api_basic_auth_username: admin
    es_api_basic_auth_password: admin
    ansible_user: ubuntu
    es_plugins:
     - plugin: ingest-geoip

- hosts: data_nodes1
  become: yes
  roles:
    - role: elasticsearch
  vars:
      es_instance_name: "node2"
      es_api_port: 9201
      es_config:
        discovery.zen.ping.unicast.hosts: "ip-172-31-25-114.us-west-2.compute.internal:9300"
        http.port: 9201
        transport.tcp.port: 9301
        node.data: true
        node.master: false
        bootstrap.memory_lock: false
        cluster.name: "hawk-cluster"
        network.host : '172.31.18.179'
      es_scripts: false
      es_api_basic_auth_username: admin
      es_api_basic_auth_password: admin
      es_templates: false
      es_version_lock: false
      es_api_port: 9201
      ansible_user: ubuntu
      es_plugins:
        - plugin: ingest-geoip
